module.exports = [
    {
        name: "Abhjit Mohapatra",
        registrationNumber: 1801227010,
        rollNumber: "CS180046",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "abhijit@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Abhipsa Mohanty",
        registrationNumber: 1801227015,
        rollNumber: "CS180095",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "abhipsa@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Abhishake Banerjee",
        registrationNumber: 1801227017,
        rollNumber: "CS180105",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "abhishake@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Abhishek Kumar",
        registrationNumber: 1801227025,
        rollNumber: "CS180117",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "abhi@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Abhishek Kumar",
        registrationNumber: 1801227026,
        rollNumber: "CS180149",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "abhikumar@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Abhishek Kumar",
        registrationNumbe: 1801227027,
        rollNumber: "CS180173",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "abhishekkumar@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Adarsh Kumar",
        registrationNumber: 1801227032,
        rollNumber: "CS180140",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "adarsh@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Adarsh Kumar sahu",
        registrationNumber: 1801227033,
        rollNumber: "CS180066",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "adarshsahu@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Adarsh Panigrahi",
        registrationNumber: 1801227034,
        rollNumber: "CS180103",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "adarsh123@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Aditya Prasad Panda",
        registrationNumber: 1801227041,
        rollNumber: "CS180062",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "aditya@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Aditya Ranjan Parida",
        registrationNumber: 1801227042,
        rollNumber: "CS180049",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "adi@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Aishee Biswas",
        registrationNumber: 1801227047 ,
        rollNumber: "CS180167",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "aishee@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Aishwarya Mohanty",
        registrationNumber: 1801227048,
        rollNumber: "CS180130",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "aishwarya@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Akankshya Tripathy",
        registrationNumber: 1801227053,
        rollNumber: "CS180125",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "akankshya@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Akhilesh Kumar Jha",
        registrationNumber: 1801227059,
        rollNumber: "CS180113",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "akhilesh@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Aman Irshad",
        registrationNumber: 1801227064,
        rollNumber: "CS180139",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "airshad@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Aman Kumar Mishra",
        registrationNumber: 1801227067,
        rollNumber: "CS180007",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "amankumar@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Amisha Dora",
        registrationNumber: 1801227071,
        rollNumber: "CS180085",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "dora@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Amisha Panigrahi",
        registrationNumber: 1801227072,
        rollNumber: "CS180152",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "amishapanigrahi@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Amritansh Soni",
        registrationNumber: 1801227079,
        rollNumber: "CS180185",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "amritansh@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Anish Sahay",
        registrationNumber: 1801227088,
        rollNumber: "CS180041",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "anish@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Anita Kumari Jena",
        registrationNumber: 1801227089,
        rollNumber:"CS180077",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "anita@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ankit Kumar Chaini",
        registrationNumber: 1801227094,
        rollNumber: "CS180061",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "ankitchaini@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ankit Kumar Tiwari",
        registrationNumber: 1801227095,
        rollNumber:"CS180089",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "twari@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ankit Singh",
        registrationNumber: 1801227096,
        rollNumber: "CS180151",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "asingh@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ankita Pattnaik",
        registrationNumber: 1801227098,
        rollNumber: "CS180134",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "ankita@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Anshika Priyadarshini",
        registrationNumber: 1801227100,
        rollNumber: "CS180090",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "anshika@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Anubhav Parida",
        registrationNumber: 1801227103,
        rollNumber: "CS180051",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "anubhav@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Aparnna Dash",
        registrationNumber: 1801227112,
        rollNumber: "CS180107",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "aparna@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Asish Mohapatra",
        registrationNumber: 1801227124,
        rollNumber: "CS1801150",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "asish@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ashutosh Pattanaik",
        registrationNumber: 1801227132,
        rollNumber: "CS180068",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "ashutosh@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ashutosh Sendha",
        registrationNumber: 1801227133,
        rollNumber: "CS180008",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "sendha@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Asish Kumar Dash",
        registrationNumber: 1801227135,
        rollNumber: "CS180156",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "asishdash@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ayush Parida",
        registrationNumber: 1801227146,
        rollNumber: "CS180165",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "ayush@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ayush Rath",
        registrationNumber: 1801227148,
        rollNumber: "CS180078",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "rath@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "B Mukta Tanaya",
        registrationNumber: 1801227150,
        rollNumber: "CS180102",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "mukta@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "B N Aparna Baral",
        registrationNumber: 1801227151,
        rollNumber: "CS180006",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "bn1123@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Barsharanee Sahoo",
        registrationNumber: 1801227153,
        rollNumber: "CS180030",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "barsha@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Bharat Subham",
        registrationNumber: 1801227157,
        rollNumber: "CS180170",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "bharat@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Bhavesh Srivas",
        registrationNumber: 1801227158,
        rollNumber: "CS180141",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "bhavesh@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Bisakh Ranjan Barik",
        registrationNumber: 1801227161,
        rollNumber: "CS180023",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "bisakh@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Biswajeet Sahoo",
        registrationNumber: 1801227164,
        rollNumber: "CS180014",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "biswa@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Biswajit Das",
        registrationNumber: 1801227123,
        rollNumber: "CS180115",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "jeet.biswa@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "C H Bala Sai",
        registrationNumber: 1801227169,
        rollNumber: "CS180039",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "dalasai@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "CH V S S Komal Kumar",
        registrationNumber: 1801227170,
        rollNumber: "CS180088",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "komalkumar@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Chandra Prakash Kumar",
        registrationNumber: 1801227174,
        rollNumber: "CS180108",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "chandra@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Chatrapati Kashyap",
        registrationNumber: 1801227176,
        rollNumber: "CS180159",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "chattrapati@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Chiranjeeb Dash",
        registrationNumber: 1801227178,
        rollNumber: "CS180017",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "chiru@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Deepak Kumar Sahoo",
        registrationNumber: 1801227182,
        rollNumber: "CS180138",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "deepak@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Dhiraj Kumar",
        registrationNumber: 1801227184,
        rollNumber: "CS180150",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "dhiraj@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Dikshant Mohapatra",
        registrationNumber: 1801227186,
        rollNumber: "CS180096",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "dikshant@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Divanti Neogi",
        registrationNumber: 1801227187,
        rollNumber:"CS180027",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "divanti@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Divya Swaroopa Luha",
        registrationNumber: 1801227189,
        rollNumber: "CS180086",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "divya@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Gagan Bihari Nisal",
        registrationNumber: 1801227195,
        rollNumber: "CS180123",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "gagan@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Harsh Kumar",
        registrationNumber: 1801227205,
        rollNumber: "CS180111",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "harsh@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Harsh Sharma",
        registrationNumber: 1801227206,
        rollNumber: "CS180143",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "sharmaji@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Hemananda Behera",
        registrationNumber: 1801227208,
        rollNumber: "CS180147",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "hemanand@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Hemant Raj",
        registrationNumber: 1801227209,
        rollNumber: "CS180128",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "hemant@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ikramul Iqbal",
        registrationNumber: 1801227212,
        rollNumber: "CS180166",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "ikramul@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Ippsa Mahana",
        registrationNumber: 1801227214,
        rollNumber: "CS180121",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "ippsa@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Jaekisen Agarwal",
        registrationNumber: 1801227219,
        rollNumber: "CS180110",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "jackie@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Jagat Jyoti Swain",
        registrationNumber: 1801227221,
        rollNumber: "CS180063",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "jagat@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Jaidipto Palit",
        registrationNumber: 1801227224,
        rollNumber: "CS180172",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "jaidipto@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Jajatee Nandinee Sahoo",
        registrationNumber: 1801227194,
        rollNumber: "CS180225",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "googlysahoo9@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Jyoti Prakash Mohanta",
        registrationNumber: 1801227230,
        rollNumber: "CS180056",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "jyotimohanta@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Jyoti Ranjan Rout",
        registrationNumber: 1801227231,
        rollNumber: "CS180082",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "jrout@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Jyoti Ranjan Swain",
        registrationNumber: 1801227233,
        rollNumber: "CS180022",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "swainjyoti@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Jyotirmay Giri",
        registrationNumber: 1801227236,
        rollNumber: "CS180079",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "giri@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
        },
        {
        name: "Kalivarapu Pawan Kumar",
        registrationNumber: 1801227238,
        rollNumber: "CS180076",
        branch: "Computer Science and Engineering",
        year: 2018,
        email: "pawan@gmail.com",
        phoneNumber: 9853872597	,
        street: "plot no. 121, chakeisihani",
        landmark: "near ugalamani temple",
        city: "Bhubaneswar",
        state: "Odisha",
        country: "India"
    }
        
]